name: Combat-Master
version: v2.0.0
main: com.melut.combatmaster.CombatMaster
api-version: 1.20
author: Melut
description: Advanced combat hit counter plugin with sounds and leaderboard
softdepend: [PlaceholderAPI]

commands:
  combatmaster:
    description: Combat Master ana komutu. Oyuncular /combatmaster stats, /combatmaster top
    usage: /<command> [reload|stats|reset|info|top]
    aliases: [cm, combat]
    permission: combatmaster.use

permissions:
  combatmaster.admin:
    description: Admin permissions
    default: op
  combatmaster.use:
    description: Oyuncular için temel kullanım (stats, top)
    default: true
##############################################################################
#                                                                            #
#  This plugin was developed by [Melüt].                                     #
#                                                                            #
#  For support, contributions, or to connect:                                #
#  Discord Community: [https://discord.com/users/871721944268038175]         #
#  GitHub Repository: [https://github.com/amhunter1]                         #
#                                                                            #
#  Thank you for using this plugin!                                          #
#                                                                            #
##############################################################################